### ISSUE TITLE
pip install -v -e . has some problem

### ISSUE THREAD

**Issue by SiHengHeHSH** [JiayuZou2020/DiffBEV#11]
pip install -v -e .
Using pip 23.3.1 from /home/hsh/anaconda3/envs/diffbev/lib/python3.8/site-packages/pip (python 3.8)
Obtaining file:///home/hsh/2024/DiffBEV
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/hsh/2024/DiffBEV/setup.py", line 177, in <module>
      'all': parse_requirements('requirements.txt'),
    File "/home/hsh/2024/DiffBEV/setup.py", line 97, in parse_requirements
      packages = list(gen_packages_items())
    File "/home/hsh/2024/DiffBEV/setup.py", line 85, in gen_packages_items
      for info in parse_require_file(require_fpath):
    File "/home/hsh/2024/DiffBEV/setup.py", line 80, in parse_require_file
      for info in parse_line(line):
    File "/home/hsh/2024/DiffBEV/setup.py", line 54, in parse_line
      info['package'] = line.split('#egg=')[1]
  IndexError: list index out of range
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by northpoleforce** [comment]
Hi! @SiHengHeHSH  Hope to help you.
u can edit `DiffBEV/setup.py` to
```
# if line.startswith('-e '):
if line.startswith('-e ') and '#egg=' in line:
```
then, this problem is fixed, but it lead a new problem  here #12 !

**Comment by SiHengHeHSH** [comment]
Thank you very much! The code also lacks of the config file so that it compleletely cannot be reproduced successfully.
